baseURL: "https://www.chrislockard.net/"
title: Unl0ckd
pagination.PagerSize: 20
copyright: "© Chris Lockard"
theme: ["PaperMod"]
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

outputs:
  home:
    - HTML
    - JSON
    - RSS

minify:
  disableXML: true
  minifyOutput: false

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Unl0ckd
  description: "The intersection of Faith, Liberty, Security, Privacy, Technology, and Family"
  keywords:
    [
      Blog,
      Portfolio,
      Faith,
      Privacy,
      Security,
      Cyber,
      CyberSecurity,
      Family,
      Liberty,
    ]
  author: Chris
  # author: ["Me", "You"] # multiple authors
  # images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light, auto
  disableThemeToggle: false
  #relativeURLs: true
  #canonifyURLs: true
  ShowReadingTime: true
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowFullTextinRSS: false
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: true
  #editPost:
  #  URL: "https://github.com/chrislockard/chrislockard.net"
  #  Text: "Suggest Changes" # edit text
  #  appendFilePath: true # to append file path to Edit link
  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "/favicon.ico"
    favicon16x16: "favicon-16x16.png"
    favicon32x32: "favicon-32x32.png"
    apple_touch_icon: "apple-touch-icon.png"
    safari_pinned_tab: "favicon-32x32.png"
  social:
    twitter: "https://twitter.com/unl0ckd"
    mastodon: "https://fosstodon.org/web/@unl0ckd"
    stackoverflow: "https://stackoverflow.com/users/15501625/unl0ckd"
    github: "https://github.com/chrislockard"
    matrix: "https://matrix.to/#/@unl0ckd:matrix.org"
    email: "mailto:blog@chrislockard.net"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
menu:
  main:
    - identifier: about
      name: About
      url: /about
      weight: 05
    - identifier: categories
      name: Categories
      url: /categories
      weight: 10
    - identifier: tags
      name: Tags
      url: /tags
      weight: 20
    - identifier: posts
      name: Posts
      url: /post
      weight: 30
    - identifier: privacy
      name: Privacy
      url: /privacy
      weight: 40
    - identifier: search
      name: Search
      url: /search
      weight: 50
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
# pygmentsUseClasses: true
# markup:
#     highlight:
#         # anchorLineNos: true
#         codeFences: true
#         guessSyntax: true
#         lineNos: true
#         style: monokai
