baseURL: "https://www.chrislockard.net/"
title: "🔓 Unl0ckd "
pagination.PagerSize: 20
copyright: "© Chris Lockard"
theme: ["PaperMod"]
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

outputs:
  home:
    - HTML
    - JSON
    - RSS
    - humanstxt

outputFormats:
  humanstxt:
    baseName: humans
    isPlainText: true
    mediaType: text/plain

minify:
  disableXML: true
  minifyOutput: false

params:
  env: production
  title: Unl0ckd
  description: "The intersection of Faith, Liberty, Security, Privacy, Technology, and Family"
  keywords:
    - Blog
    - Portfolio
    - Faith
    - Privacy
    - Security
    - Cyber
    - CyberSecurity
    - Family
    - Liberty
  author: Chris
  DateFormat: "January 2, 2006"
  defaultTheme: auto
  disableThemeToggle: false
  ShowReadingTime: true
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowFullTextinRSS: false
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: true
  ignoreLogs:
    - warning-goldmark-raw-html
  assets:
    favicon: "/images/icons/favicon.ico"
    favicon16x16: "/images/icons/favicon-16x16.png"
    favicon32x32: "/images/icons/favicon-32x32.png"
    apple_touch_icon: "/images/icons/apple-touch-icon.png"
    safari_pinned_tab: "/images/icons/favicon-32x32.png"
  social:
    twitter: "https://twitter.com/unl0ckd"
    mastodon: "https://fosstodon.org/web/@unl0ckd"
    stackoverflow: "https://stackoverflow.com/users/15501625/unl0ckd"
    github: "https://github.com/chrislockard"
    matrix: "https://matrix.to/#/@unl0ckd:matrix.org"
    email: "mailto:blog@chrislockard.net"
  cover:
    hidden: true
    hiddenInList: true
    hiddenInSingle: true
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

menu:
  main:
    - identifier: about
      name: About
      url: /about
      weight: 01
    - identifier: categories
      name: Categories
      url: /categories
      weight: 10
    - identifier: links
      name: Links
      url: /links
      weight: 20
    - identifier: archive
      name: Archive
      url: /archive
      weight: 30
    - identifier: privacy
      name: Privacy
      url: /privacy
      weight: 40
    - identifier: search
      name: Search
      url: /search
      weight: 50

markup:
  goldmark:
    renderer:
      unsafe: true
